# Generated by Django 5.1.7 on 2025-03-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(help_text='Nome do usuário', max_length=255, verbose_name='Usuário')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
            },
        ),
    ]
