# Generated by Django 5.1.7 on 2025-03-21 00:20

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversas', '0003_mensagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetorDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vetores', to='conversas.documento')),
            ],
        ),
    ]
