# Generated by Django 5.1.7 on 2025-03-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversas', '0006_auto_20250322_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetordocumento',
            name='page_content',
            field=models.TextField(blank=True, help_text='Conteúdo da página', null=True, verbose_name='Conteúdo da página'),
        ),
    ]
