# Generated by Django 5.1.7 on 2025-07-23 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversas', '0007_vetordocumento_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens', to='conversas.documento'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='erro',
            field=models.BooleanField(default=False),
        ),
    ]
